export const ERROR_CODES = [
  'PROJECT_NOT_INITIALIZED', 'CACHE_SCHEMA_UNSUPPORTED', 'CACHE_BUSY', 'CACHE_HASH_COLLISION', 'REGISTRY_COLLISION', 'IMPORT_CANCELLED', 'RESOURCE_LIMIT_EXCEEDED', 'ARCHIVE_MALFORMED', 'CANVAS_MISSING', 'INVALID_HEADER', 'UNSUPPORTED_FORMAT_VERSION', 'DECOMPRESSION_FAILED', 'DOCUMENT_INVALID', 'DUPLICATE_NODE_ID', 'INVALID_PARENT', 'GRAPH_CYCLE', 'UNREACHABLE_NODE', 'BLOB_INVALID', 'ASSET_HASH_MISMATCH', 'URL_INVALID', 'NODE_ID_INVALID', 'INSTANCE_PATH_UNSUPPORTED', 'DOCUMENT_NOT_IMPORTED', 'NODE_NOT_FOUND', 'TEXT_STYLE_INVALID',
] as const;
export type ErrorCode = typeof ERROR_CODES[number];
